#!/usr/bin/env node

'use strict'

var clc = require('cli-color')

var def = require('./commands/def.json')
var input = require('./commands/input.js')
var getScreen = require('./commands/cache.js').getScreen

var helpTextOn = true

function next() {
  var text = [
    JSON.stringify(def, null, 2),
    'q: toggle help text',
    'w: up',
    's: down',
    'a: left',
    'd: right',
    'r: zoom in',
    'f: zoom out',
    't: more iterations',
    'g: less iterations',
    'o: quit',
    ''
    ].join('\n')
  var output = clc.moveTo(0, 0) + getScreen(def, clc.width - 1, clc.height)
  if (helpTextOn) {
    output += clc.moveTo(0, 0) + clc.xterm(8)(text)
  }
  process.stdout.write(output)
}

process.stdin.setRawMode(true)
process.stdin.resume()
process.stdin.on('data', function(data) {
  var key = data.toString()[0]
  if (key === 'o') {
    console.log(clc.reset)
    process.exit()
  } else if (key === 'q') {
    helpTextOn = !helpTextOn
  }
  def = input.keyPress(def, key)
  next()
})

next()
